[profile.default]
src = "src"
out = "out"
libs = ["lib"]
evm_version = "cancun"
always_use_create_2_factory = true # Use Foundry's create2 factory in tests(https://github.com/foundry-rs/foundry/pull/6656)

gas_reports_ignore = ["MockDelayedInclusionStore", "MockCheckpointTracker", ""]

[fmt]
sort_imports = true
wrap_comments = true

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
