[profile.default]
src = "src"
out = "out"
libs = ["lib"]
evm_version = "cancun"
always_use_create_2_factory = true
sender = "0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266"

gas_reports_ignore = ["MockDelayedInclusionStore", "MockCheckpointTracker", "SampleDepositProof", "SampleProof", "MockInbox", "MockERC20", "MockVerifier"]

remappings = [
    "@optimism/=lib/optimism/",
    "@vendor/=src/vendor/",
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/"
]

fs_permissions = [{ access = "write", path = "./gas-reports/"}]

[fmt]
sort_imports = true
wrap_comments = true

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
