[profile.default]
src = "src"
out = "out"
libs = ["lib"]
evm_version = "cancun"
always_use_create_2_factory = true
rpc_endpoints = { L1 = "http://localhost:8545", L2 = "http://localhost:8546" }

[fmt]
sort_imports = true
wrap_comments = true

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
